version: "3"

services:
  app:
    build: ./
    environment:
      TWITTER_API_KEY: <your_twitter_api_key>
      TWITTER_API_SECRET: <your_twitter_api_secret_key>
    ports:
      - "3001:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail 0.0.0.0:8000 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
